"""empty message

Revision ID: 641b464ae951
Revises: 
Create Date: 2025-08-18 11:45:14.755225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641b464ae951'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Blogs_Posts_data',
    sa.Column('s_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('post_title', sa.Text(), nullable=False),
    sa.Column('post_content', sa.Text(), nullable=False),
    sa.Column('date_and_time', sa.Text(), nullable=False),
    sa.Column('post_token', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('s_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Blogs_Posts_data')
    # ### end Alembic commands ###
